AWSTemplateFormatVersion: "2010-09-09"
Description: A template for assigning IAM role to lambda and SQS.
Resources:
  SQSLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: AllowSQSAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource: !ImportValue SQSQueueARN
Outputs:
  MyLambdaPolicyARN:
    Description: The ARN of policy for receiving messages from SQS.
    Value: !GetAtt SQSLambdaExecutionRole.Arn
    Export:
      Name: LambdaSQSRoleArn