AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TopicName:
    Description: "Name for your SNS topic"
    Type: String
    Default: "SNS2SQS"
Resources:
  SNSTopic:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Ref TopicName
      KmsMasterKeyId: alias/aws/sns
      Subscription:
        - Endpoint: !ImportValue SQSQueueARN
          Protocol: "sqs"
  SQSPermission:
    Type: "AWS::SQS::QueuePolicy"
    Properties:
      PolicyDocument:
        Statement:
          - Sid: "AllowSNSAccess"
            Effect: Allow
            Principal:
              Service: "sns.amazonaws.com"
            Action:
              - "sqs:SendMessage"
            Resource: !ImportValue SQSQueueARN
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSTopic
      Queues:
        - !ImportValue SQSUrl