Description: Template that creates a role for lambda function with basic execution policy
Parameters:
  RoleName:
    Description: Add Name for the role you are creating
    Type: String
    Default: LambdaDynamoDBcrossAccountRole
Resources:
  LambdaDynamoDBcrossAccountRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal: 
                AWS: "arn:aws:iam::975050083676:role/LambdaDynamoDbProcessorRole"  
              Action:
                - "sts:AssumeRole"
      Description: Role for lambda service
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        - "arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess"
      RoleName: !Ref RoleName
      Tags:
           - Key: app
             Value: ServerlessWithDynamoDB
Outputs:
  OutputName:
    Description: ARN of the role created
    Value: !GetAtt LambdaDynamoDBcrossAccountRole.Arn
    Export:
      Name: LambdaRoleArn
